name: Build and Deploy Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython virtualenv
        pip install kivy
        pip install buildozer
        choco install -y android-sdk
        choco install -y openjdk8

    - name: Initialize Buildozer
      run: |
        buildozer init

    - name: Modify Buildozer Spec File
      run: |
        (Get-Content buildozer.spec).replace('# (str) Title of your application', 'title = MyKivyApp') | Set-Content buildozer.spec
        (Get-Content buildozer.spec).replace('# (str) Package name', 'package.name = mykivyapp') | Set-Content buildozer.spec
        (Get-Content buildozer.spec).replace('# (str) Source code URL (default: None)', 'source.url = https://github.com/<your-repo>') | Set-Content buildozer.spec
        (Get-Content buildozer.spec).replace('# (list) Application requirements', 'requirements = python3,kivy') | Set-Content buildozer.spec
        (Get-Content buildozer.spec).replace('# (str) Presplash image filename', 'presplash.filename = %(source.include_exts)') | Set-Content buildozer.spec
        (Get-Content buildozer.spec).replace('# (list) Permissions', 'permissions = INTERNET') | Set-Content buildozer.spec

    - name: Build APK
      env:
        BUILD_ROOT_WARNING: 1  # Set environment variable to bypass the prompt
      run: |
        set BUILD_ROOT_WARNING=1
        buildozer -v android debug
        dir bin

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: bin/*.apk
