name: Build and Deploy Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev
        pip3 install --user --upgrade cython virtualenv
        sudo apt-get update  # Update the package list
        sudo apt-get install -y libtinfo5

    - name: Install Buildozer
      run: |
        pip3 install buildozer

    - name: Build APK
      run: |
        buildozer -v android debug
        # Ensure the APK is generated in the bin directory

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/
