name: Build and Deploy Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython virtualenv
        pip install kivy
        pip install buildozer
        choco install -y android-sdk
        choco install -y openjdk8

    - name: Patch Buildozer Script to Skip Root Check
      run: |
        $content = Get-Content C:\hostedtoolcache\windows\Python\3.12.8\x64\Lib\site-packages\buildozer\__init__.py
        $content = $content -replace 'input\(.+\)', 'print("Running as root in non-interactive mode")'
        Set-Content C:\hostedtoolcache\windows\Python\3.12.8\x64\Lib\site-packages\buildozer\__init__.py -Value $content

    - name: Build APK
      env:
        BUILDOZER_IGNORE_ERRORS: 1
      run: |
        set BUILDOZER_IGNORE_ERRORS=1
        buildozer -v android debug
        dir bin

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk
